// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXwrELDf2fd7E3afzbxXzfnIpowx9FT4w',
    appId: '1:945628762135:web:721b53e280dce5238b4c52',
    messagingSenderId: '945628762135',
    projectId: 'fruit-hub-985a3',
    authDomain: 'fruit-hub-985a3.firebaseapp.com',
    storageBucket: 'fruit-hub-985a3.firebasestorage.app',
    measurementId: 'G-BTQJQHTWQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_2Rlg358S1p3YVEPNcbN9mF3RxwjAwzY',
    appId: '1:945628762135:android:fbcaff08cc69f3eb8b4c52',
    messagingSenderId: '945628762135',
    projectId: 'fruit-hub-985a3',
    storageBucket: 'fruit-hub-985a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidGRSGlsvFa3DIsj9SY8nifG5pYQAmuU',
    appId: '1:945628762135:ios:698e680aad1830538b4c52',
    messagingSenderId: '945628762135',
    projectId: 'fruit-hub-985a3',
    storageBucket: 'fruit-hub-985a3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBidGRSGlsvFa3DIsj9SY8nifG5pYQAmuU',
    appId: '1:945628762135:ios:698e680aad1830538b4c52',
    messagingSenderId: '945628762135',
    projectId: 'fruit-hub-985a3',
    storageBucket: 'fruit-hub-985a3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXwrELDf2fd7E3afzbxXzfnIpowx9FT4w',
    appId: '1:945628762135:web:a9e6d392886a795a8b4c52',
    messagingSenderId: '945628762135',
    projectId: 'fruit-hub-985a3',
    authDomain: 'fruit-hub-985a3.firebaseapp.com',
    storageBucket: 'fruit-hub-985a3.firebasestorage.app',
    measurementId: 'G-ZD4HLCVFP2',
  );
}
